saved_models_dir = '/home/zhiwei/source/SPAct/anonymization_training/saved_models/vqgan'
logs = '/home/zhiwei/source/SPAct/anonymization_training/logs/vqgan'
dataset_list_dir = '/home/zhiwei/source/SPAct/dataset_list/'
save_dir_action = '/home/zhiwei/source/SPAct/anonymization_training/action_logs_vqgan'
save_dir_privacy = '/home/zhiwei/source/SPAct/anonymization_training/privacy_logs_vqgan'
save_dir_minmax = '/home/zhiwei/source/SPAct/anonymization_training/minmax_logs_vqgan'

save_dir_action_da = '/home/zhiwei/source/SPAct/anonymization_training/action_da_logs_vqgan'
save_dir_privacy_da = '/home/zhiwei/source/SPAct/anonymization_training/experiments/privacy_da_logs_vqgan'
save_dir_vqgan_da = '/home/zhiwei/source/SPAct/anonymization_training/experiments/vqgan_da_logs'