#!/bin/bash
cd ../..
OMP_NUM_THREADS=4 CUDA_VISIBLE_DEVICES=0,1,4,5 torchrun --nproc_per_node 4 --master_port 29506 vqgan_minmax.py \
    --src 'hmdb' \
    --tar 'ucf' \
    --num_frames 16 \
    --sample_every_n_frames 2 \
    --num_workers 8 \
    --batch_size 8 \
    --v_batch_size 8 \
    --train_backbone \
    --architecture 'resnet50' \
    --learning_rate_fa 0.0001 \
    --learning_rate_fb 0.001 \
    --learning_rate_ft 0.001 \
    --learning_rate_disc 0.001 \
    --learning_rate_domain 0.001 \
    --learning_rate_triplet 0.001 \
    --num_epochs 200 \
    --val_freq 5 \
    --recon_freq 5 \
    --reso_h 128 \
    --reso_w 128 \
    --triple 1 \
    --embedding_dim_dynamic 128 \
    --embedding_dim_static 128 \
    --n_codes_dynamic 16384 \
    --n_codes_static 2048 \
    --n_hiddens 32 \
    --downsample 4 8 8 \
    --disc_channels 64 \
    --disc_layers 3 \
    --discriminator_iter_start 200 \
    --recon_iter_start 0 \
    --triplet_iter_start 15 \
    --domain_iter_start 25 \
    --disc_loss_type hinge \
    --image_gan_weight 1.0 \
    --video_gan_weight 1.0 \
    --l1_weight 4.0 \
    --gan_feat_weight 4.0 \
    --perceptual_weight 4.0 \
    --action_weight 1.0 \
    --privacy_weight 1.0 \
    --weight_class_action 1 \
    --weight_class_privacy 0 \
    --restart_thres 1.0 \
    --no_random_restart \
    --norm_type batch \
    --padding_type replicate \
    --self_pretrained_vqgan '/home/zhiwei/source/SPAct/VQGAN_anonymization/logs/vqgan_pretrain/hmdb_frames_16_every_2_bs_8_lr_0.0001_codes_s_2048_codes_d_16384_dis_iter_50_tri_iter_30/model_130.pth' \
    --self_pretrained_action '/home/zhiwei/source/SPAct/anonymization_training/action_da_logs_vqgan/train_action_da_hmdb2ucf_frames_16_bs_30_lr_0.005_optimizer_sgd_action_1.0_pseudo_1.0_entropy_1.0_domain_1.0/model_hmdb2ucf_48_acc_0.9667250437828371.pth' \
    --self_pretrained_privacy '/home/zhiwei/source/SPAct/anonymization_training/experiments/privacy_logs/train_privacy_resnet50_hmdb_frames_16_rate_2_bs_64_lr_0.005/model_hmdb_55_cMAP_0.6512181795908678.pth'